// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-YC8wbfHYoSndei2nHL4oKbrTpdM584Q',
    appId: '1:340912619868:android:c1a2b4a44098adebadc199',
    messagingSenderId: '340912619868',
    projectId: 'flutter-preps-f95b4',
    storageBucket: 'flutter-preps-f95b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5tfZbA9rm_tRKdB4qWoM1mpky1Sr1KU',
    appId: '1:340912619868:ios:4eb840b60e93ce2eadc199',
    messagingSenderId: '340912619868',
    projectId: 'flutter-preps-f95b4',
    storageBucket: 'flutter-preps-f95b4.appspot.com',
    iosBundleId: 'com.example.jdds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5tfZbA9rm_tRKdB4qWoM1mpky1Sr1KU',
    appId: '1:340912619868:ios:5c4a01180f605fcdadc199',
    messagingSenderId: '340912619868',
    projectId: 'flutter-preps-f95b4',
    storageBucket: 'flutter-preps-f95b4.appspot.com',
    iosBundleId: 'com.example.jdds.RunnerTests',
  );
}
